[build]
language = "java"
builder = "gradle"
buildCommand = "cd healsync && ./gradlew build"

[start]
cmd = "java -jar healsync/build/libs/healsync-0.0.1-SNAPSHOT.jar"

[dependencies]
packages = ["openjdk"]