[build]
  language = "java"
  builder = "gradle"
  buildCommand = "./gradlew build"

[start]
  cmd = "java -jar healsync/build/libs/healsync-0.0.1-SNAPSHOT.jar"

[dependencies]
  packages = ["openjdk-21"]
